server:
  port: 8081

spring:
  application:
    name: CatalogUi
  thymeleaf:
    cache: false # Disable caching in development for live updates

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
cart-service:
  url: http://CartService/api/cart
order-service:
  url: http://OrderService/api/order

---
spring:
  config:
    activate:
      on-profile: local
catalog-service:
  url: http://localhost:8080/api/product
cart-service:
  url: http://localhost:8082/api/cart
order-service:
  url: http://localhost:8083/api/order

