server:
  port: 8081

spring:
  application:
    name: CatalogUi
  thymeleaf:
    cache: false # Disable caching in development for live updates
  web:
    resources:
      cache:
        period: 0 # Disable static resource caching in development for live updates

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
catalog-service:
  url: http://CatalogService/api/product
cart-service:
  url: http://CartService/api/cart
order-service:
  url: http://OrderService/api/order
